### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [OS-IS/ai202-larin#3]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
1) Відомо, що безпечна клієнт-серверна взаємодія може забезпечуватися через наступні ключи: 
відкритий ключ клієнта, закритий ключ клієнта, відкритий ключ сервера, закритий ключ сервера. 
Вкажіть, будь ласка, який ключ вами було використано під час налаштування безпечного оновлення 
GitHub-репозиторію змінами з локального Git-репозиторію.

**Comment by larinmykhailo** [comment]
був використаний відкритий (публічний) ключ клиєнта.
![image](https://github.com/user-attachments/assets/413cf30e-54c4-4515-991e-3b1d89a062e3)

**Comment by oleksandrblazhko** [comment]
2 бали
